name: puj_ticket
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/bus-logo.png
  image_dark: assets/images/bus-logo.png

android_12:
  image: assets/images/bus-logo.png
  icon_background_color: "#f7f6f1"
  image_dark: assets/images/bus-logo.png
  icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true

  assets:
    - assets/images/bus-logo.png
    - assets/images/bus.png
    - assets/images/BusStop3.png
    - assets/images/Forgot-password.png
    - assets/images/Reset-password.png
    - assets/images/onboarding_images/
